# SPDX-FileCopyrightText: 2003-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

version = 1

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    ".mailmap",
    "AUTHORS.md",
    "README.md",
    "media/.htaccess",
    "media/images/**",
    "requirements.txt",
    "weechat/*/_i18n_*.py",
    "weechat/*/migrations/**",
    "weechat/fixtures/*.json",
    "weechat/templates/**",
]
SPDX-FileCopyrightText = "2003-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "media/css/bootstrap*.css",
    "media/js/bootstrap*.js",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "media/js/jquery*.js",
]
SPDX-FileCopyrightText = "OpenJS Foundation and other contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "media/pgp/*",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
