# Generated by Django 2.2.28 on 2023-04-16 09:11

from django.db import migrations, models

SQL_INSERT_PROJECTS = """
INSERT INTO common_project (visible, name, description, priority) VALUES
(TRUE, 'weechat', 'WeeChat', 100),
(TRUE, 'weechat-relay', 'WeeChat Relay', 200),
(TRUE, 'qweechat', 'QWeeChat', 300);
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.RunSQL(SQL_INSERT_PROJECTS),
    ]
