# Generated by Django 2.2.28 on 2023-04-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('wsa', models.CharField(max_length=64)),
                ('cve', models.CharField(blank=True, max_length=64)),
                ('cwe_id', models.IntegerField(default=0)),
                ('cwe_text', models.CharField(max_length=64)),
                ('cvss_vector', models.CharField(max_length=64)),
                ('cvss_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tracker', models.CharField(blank=True, max_length=64)),
                ('affected', models.CharField(blank=True, max_length=64)),
                ('fixed', models.CharField(blank=True, max_length=32)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('commits', models.CharField(blank=True, max_length=1024)),
                ('scope', models.CharField(max_length=64)),
                ('issue', models.TextField()),
                ('description', models.TextField()),
                ('mitigation', models.TextField(blank=True)),
                ('credit', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('directory', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('devel', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Version')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
