# Generated by Django 2.2.28 on 2023-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(max_length=8),
        ),
        migrations.RunSQL(
            "ALTER TABLE doc_language ADD COLUMN id SERIAL PRIMARY KEY;",
            state_operations=[
                migrations.AddField(
                    model_name='language',
                    name='id',
                    field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
                    preserve_default=False,
                ),
            ],
        ),
    ]
