# Generated by Django 2.2.28 on 2023-04-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('doc', '0004_security_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Project'),
            preserve_default=False,
        ),
    ]
