# Generated by Django 4.2.28 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0006_doc_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="cwe_text",
            field=models.CharField(max_length=256),
        ),
    ]
