# Generated by Django 2.2.28 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=256)),
                ('mail', models.EmailField(max_length=256)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
