# Generated by Django 2.2.28 on 2023-04-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('nick', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('codename', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('arch', models.CharField(max_length=128)),
                ('build_frequency', models.IntegerField(default=24)),
                ('message', models.CharField(blank=True, max_length=1024)),
                ('priority', models.IntegerField(default=0)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debian.Builder')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debian.Version')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
