# Generated by Django 2.2.28 on 2023-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version_string',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RunSQL("UPDATE dev_task SET version_string = version_id;"),
        migrations.RemoveField(
            model_name='task',
            name='version',
        ),
    ]
