# Generated by Django 2.2.28 on 2023-04-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_task_version_1'),
        ('download', '0005_release_package_version_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='download.Release'),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE dev_task task SET version_id = (SELECT id FROM download_release WHERE download_release.version = task.version_string);"),
        migrations.RemoveField(
            model_name='task',
            name='version_string',
        ),
    ]
