# Generated by Django 2.2.28 on 2023-04-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_remove_release_progress_todo'),
        ('dev', '0002_task_version_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='version_string',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['version_string', '-type__priority']},
        ),
        migrations.RunSQL("UPDATE download_package SET version_string = version_id;"),
        migrations.RemoveField(
            model_name='package',
            name='version',
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(max_length=64),
        ),
        migrations.RunSQL(
            "ALTER TABLE download_release ADD COLUMN id SERIAL PRIMARY KEY;",
            state_operations=[
                migrations.AddField(
                    model_name='release',
                    name='id',
                    field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='download.Release'),
            preserve_default=False,
        ),
    ]
