# Generated by Django 2.2.28 on 2023-04-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_release_package_version_1'),
    ]

    operations = [
        migrations.RunSQL("UPDATE download_package pkg SET version_id = (SELECT id FROM download_release WHERE download_release.version = pkg.version_string);"),
    ]
