# Generated by Django 2.2.28 on 2023-04-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('download', '0005_release_package_version_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.Project'),
            preserve_default=False,
        ),
    ]
