# Generated by Django 5.2.16 on 2026-07-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0007_remove_release_securityfix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="security_issues_fixed",
        ),
    ]
