# Generated by Django 2.2.28 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('md5sum', models.CharField(blank=True, max_length=32)),
                ('sha512sum', models.CharField(blank=True, max_length=128)),
                ('desc', models.CharField(blank=True, max_length=1024)),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(max_length=256)),
                ('mail', models.CharField(max_length=256)),
                ('added', models.DateTimeField()),
                ('updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
