# SPDX-FileCopyrightText: 2020-2026 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  - push
  - pull_request

jobs:

  checks:

    env:
      POEXAM_VERSION: "0.1.1"

    strategy:
      matrix:
        os:
          - ubuntu-26.04

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v7

    - name: Install gettext
      run: sudo apt-get install gettext

    - name: Install poexam
      run: |
        cd "$RUNNER_TEMP"
        curl --silent --show-error --fail --location --remote-name-all \
          "https://github.com/poexam/poexam/releases/download/v$POEXAM_VERSION/poexam-linux-x86_64.tar.gz" \
          "https://github.com/poexam/poexam/releases/download/v$POEXAM_VERSION/poexam-linux-x86_64.sha256"
        sha256sum --check poexam-linux-x86_64.sha256
        tar --extract --file poexam-linux-x86_64.tar.gz
        sudo install -m 0755 poexam-linux-x86_64/poexam /usr/local/bin/poexam

    - name: Check gettext files
      run: make gettext

  build:

    strategy:
      matrix:
        os:
          - ubuntu-26.04
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v7

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: make lint
